ppars/apps/notification/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from views import SpamMessageCreate, CustomPreChargeMessageDetail, WelcomeEmailList, WelcomeEmailCreate,\
    WelcomeEmailEdit, welcome_message_delete


urlpatterns = patterns('',
    url(r'^create/$', login_required(SpamMessageCreate.as_view()), name='sms_create'),
    url(r'^precharge/$', login_required(CustomPreChargeMessageDetail.as_view()), name='custom_message'),
    url(r'^welcome_email/$', login_required(WelcomeEmailList.as_view()), name='welcome_email'),
    url(r'^welcome_email_create/$', login_required(WelcomeEmailCreate.as_view()), name='welcome_email_create'),
    url(r'^welcome_email_edit/(?P<pk>\d+)/$', login_required(WelcomeEmailEdit.as_view()), name='welcome_email_edit'),
    url(r'^welcome_message_delete/(?P<pk>\d+)/$', login_required(welcome_message_delete),
        name='welcome_message_delete'),
)

ppars/apps/price/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from ppars.apps.price.views import PlanSellingPriceList, PlanSellingPriceUpdate


urlpatterns = patterns('',
    url(r'^/$', login_required(PlanSellingPriceList.as_view()), name="plan_selling_price_list"),
    url(r'^/(?P<pk>\d+)/$', login_required(PlanSellingPriceUpdate.as_view()), name='plan_selling_price_update'),
)

ppars/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.conf.urls.static import static
from ppars.apps.accounts.views import UserList, UserCreate, UserUpdate, \
    UserDelete
from ppars.apps.charge.views import ChargeList, ChargeDetail, ajax_charge_steps, \
    ajax_mark_charge, ajax_cc_retry, ajax_cc_refund, ajax_cc_void, \
    ajax_charge_create, ajax_charges_list, ajax_change_charge_note, ajax_cc_retry_and_trans_restart
from ppars.apps.core import views
from ppars.apps.notification.views import ez_cloud_news_emails, change_ez_email_list
from ppars.apps.api import views as api


from ppars.apps.search.views import ajax_search, search, ajax_search_dropdown
# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    #url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^login/$', 'ppars.apps.accounts.views.login_user'),
    url(r'^logout.*', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    url(r'^user/password-change/$', 'django.contrib.auth.views.password_change', name="password_change"),
    url(r'^user/password-change-done/$', 'django.contrib.auth.views.password_change_done', name="password_change_done"),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'password_reset_done'}, name='password_reset'),
    #TODO normalize tokens
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
       'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done',
        name='password_reset_done'),

    url(r'^user/profile/$', login_required(views.CompanyProfileUpdate.as_view()), name="profile"),
    url(r'^change_user/$', login_required(views.change_user), name="change_user"),

    #API
    url(r'^ajax_ez_news/$', api.ajax_ez_news, name="ajax_ez_news"),

    # Ez Cloud News
    url(r'^ez_cloud_news_emails/$', login_required(ez_cloud_news_emails), name="ez_cloud_news_emails"),
    url(r'^change_ez_email_list/$', login_required(change_ez_email_list), name="change_ez_email_list"),

    url(r'^home/$', login_required(views.Home.as_view()), name="home"),
    url(r'^search/$', login_required(search), name="search"),
    url(r'^ajax_search/$', login_required(ajax_search), name="ajax_search"),
    url(r'^ajax_search_dropdown/$', login_required(ajax_search_dropdown), name="ajax_search_dropdown"),
    url(r'^ajax_refill_as_walk_in/$', login_required(views.ajax_refill_as_walk_in), name="ajax_refill_as_walk_in"),
    
    

    url(r'^customer$', login_required(views.CustomerList.as_view()), name="customer_list"),
    url(r'^customer/create/$', login_required(views.CustomerCreate.as_view()), name='customer_create'),
    url(r'^customer/(?P<pk>\d+)/$', login_required(views.CustomerUpdate.as_view()), name='customer_update'),
    url(r'^customer/(?P<pk>\d+)/delete/$', login_required(views.CustomerDelete.as_view()), name='customer_delete'),
    url(r'^customer/export/$', login_required(views.CustomerExport.as_view()), name='customer_export'),
    url(r'^customer/import/$', login_required(views.CustomerImport.as_view()), name='customer_import'),
    url(r'^customer/transactions/(?P<pk>\d+)/$', login_required(views.customer_transactions), name='customer_transactions'),
    url(r'^ajax_customer_transactions/$', login_required(views.ajax_customer_transactions), name='ajax_customer_transactions'),
    url(r'^customer/autorefills/(?P<pk>\d+)/$', login_required(views.customer_autorefills), name='customer_autorefills'),
    url(r'^ajax_customer_autorefills/$', login_required(views.ajax_customer_autorefills), name='ajax_customer_autorefills'),
    url(r'^customer/cc_charges/(?P<pk>\d+)/$', login_required(views.customer_cc_charges), name='customer_cc_charges'),
    url(r'^ajax_customer_cc_charges/$', login_required(views.ajax_customer_cc_charges), name='ajax_customer_cc_charges'),
    url(r'swipe_and_refill', login_required(views.SwipeAndRefill.as_view()), name="swipe_and_refill"),
    url(r'^ajax_check_duplicate_number/$', login_required(views.ajax_check_duplicate_number), name='ajax_check_duplicate_number'),

    url(r'^news$', login_required(views.news), name="news"),
    url(r'^news/(?P<pk>\d+)/$', login_required(views.NewsDetail.as_view()), name='news_detail'),
    url(r'^ajax_news/$', login_required(views.ajax_news), name='ajax_news'),
    url(r'^close_updates$', login_required(views.close_updates), name='close_updates'),

    url(r'^plan$', login_required(views.PlanList.as_view()), name="plan_list"),
    url(r'^plan/create/$', login_required(views.PlanCreate.as_view()), name='plan_create'),
    url(r'^plan/(?P<pk>\d+)/$', login_required(views.PlanUpdate.as_view()), name='plan_update'),
    url(r'^plan/(?P<pk>\d+)/delete/$', login_required(views.PlanDelete.as_view()), name='plan_delete'),
    url(r'^plan/export/$', login_required(views.PlanExport.as_view()), name='plan_export'),
    url(r'^plan/import/$', login_required(views.PlanImport.as_view()), name='plan_import'),

    url(r'^plan-discount$', login_required(views.PlanDiscountList.as_view()), name="plan_discount_list"),
    url(r'^plan-discount/create/$', login_required(views.PlanDiscountCreate.as_view()), name='plan_discount_create'),
    url(r'^plan-discount/(?P<pk>\d+)/$', login_required(views.PlanDiscountUpdate.as_view()), name='plan_discount_update'),

    url(r'^carrier$', login_required(views.CarrierList.as_view()), name="carrier_list"),
    url(r'^carrier/create/$', login_required(views.CarrierCreate.as_view()), name='carrier_create'),
    url(r'^carrier/(?P<pk>\d+)/$', login_required(views.CarrierUpdate.as_view()), name='carrier_update'),
    url(r'^carrier/(?P<pk>\d+)/delete/$', login_required(views.CarrierDelete.as_view()), name='carrier_delete'),
    url(r'^carrier/export/$', login_required(views.CarrierExport.as_view()), name='carrier_export'),
    url(r'^carrier/import/$', login_required(views.CarrierImport.as_view()), name='carrier_import'),

    url(r'^carrier-admin$', login_required(views.CarrierAdminList.as_view()), name="carrier_admin_list"),
    url(r'^carrier-admin/create/$', login_required(views.CarrierAdminCreate.as_view()), name='carrier_admin_create'),
    url(r'^carrier-admin/(?P<pk>\d+)/$', login_required(views.CarrierAdminUpdate.as_view()), name='carrier_admin_update'),

    url(r'^manualrefill$', login_required(views.ManualRefill.as_view()), name="manualrefill"),

    url(r'^autorefill$', login_required(views.AutoRefillList.as_view()), name="autorefill_list"),
    url(r'^autorefill/create/$', login_required(views.AutoRefillCreate.as_view()), name='autorefill_create'),
    url(r'^autorefill/(?P<pk>\d+)/$', login_required(views.AutoRefillUpdate.as_view()), name='autorefill_update'),
    url(r'^autorefill/(?P<pk>\d+)/delete/$', login_required(views.AutoRefillDelete.as_view()), name='autorefill_delete'),
    url(r'^autorefill/export/$', login_required(views.AutoRefillExport.as_view()), name='autorefill_export'),
    url(r'^autorefill/import/$', login_required(views.AutoRefillImport.as_view()), name='autorefill_import'),
    url(r'^ajax_check_for_similar_scheduled_refill/$', login_required(views.ajax_check_for_similar_scheduled_refill), name='ajax_check_for_similar_scheduled_refill'),

    url(r'^ajax_unused_pins$', login_required(views.ajax_unused_pins), name="ajax_unused_pins"),
    url(r'^unused-pin$', login_required(views.UnusedPinList.as_view()), name="unusedpin_list"),
    url(r'^unused-pin/create/$', login_required(views.UnusedPinCreate.as_view()), name='unusedpin_create'),
    url(r'^unused-pin/import/$', login_required(views.UnusedPinImport.as_view()), name='unusedpin_import'),
    url(r'^unused-pin/(?P<pk>\d+)/$', login_required(views.UnusedPinUpdate.as_view()), name='unusedpin_update'),
    url(r'^unused-pin/(?P<pk>\d+)/delete/$', login_required(views.UnusedPinDelete.as_view()), name='unusedpin_delete'),
    url(r'^ajax/ajax_mark_unusedpin/$', login_required(views.ajax_mark_unusedpin), name='ajax_mark_unusedpin'),

    url(r'^transaction$', login_required(views.TransactionList.as_view()), name="transaction_list"),
    url(r'^transaction/(?P<pk>\d+)/$', login_required(views.TransactionDetail.as_view()), name='transaction_detail'),
    url(r'^transaction/(?P<pk>\d+).json$', login_required(views.ajax_transaction), name='ajax_transaction'),

    url(r'^pin-report$', login_required(views.PinReportList.as_view()), name="pinreport_list"),
    url(r'^pin-report/(?P<pk>\d+)/$', login_required(views.PinReportDetail.as_view()), name='pinreport_detail'),
    url(r'^pin-report/compare/$', login_required(views.compare_pins_with_dollarphone), name='compare_pins_with_dollarphone'),
    url(r'^pin-report/download/(?P<order_id>\d+)/$', login_required(views.pinreport_download), name='pinreport_download'),

    url(r'^twilio_request/$', views.twilio_request, name='twilio_request'),
    url(r'^twilio_response/$', views.twilio_response, name='twilio_response'),
    url(r'^pparsb-response/(?P<pk>\d+)/$', views.pparsb_response, name='pparsb_response'),

    url(r'^confirm-dp/$', login_required(views.ConfirmDPView.as_view()), name='confirm_dp'),
    url(r'^logs/$', login_required(views.LogList.as_view()), name="log_list"),

    url(r'^import/customers/from-usaepay/$', login_required(views.import_customers_from_usaepay), name='import_customers_from_usaepay'),
    url(r'^import/customers/from-redfin/$', login_required(views.import_customers_from_redfin), name='import_customers_from_redfin'),

ppars/apps/accounts/models.py
from django.db import models

# Create your models here.

ppars/apps/card/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from encrypted_fields import EncryptedCharField, EncryptedIntegerField

from ppars.apps.core.fields import BigForeignKey
from ppars.apps.core.models import Customer


class Card(models.Model):
    customer = BigForeignKey(Customer, related_name='cards', on_delete=models.CASCADE, null=True)
    number = EncryptedCharField(max_length=255)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    last4_number = models.IntegerField(blank=True)
    expiration_year = EncryptedIntegerField(max_length=255)
    expiration_month = EncryptedIntegerField(max_length=255)

    cvv = EncryptedCharField(max_length=255)

    created = models.DateTimeField("Created at", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Updated at", auto_now=True)

    class Meta:
        ordering = ('number',)

    def __unicode__(self):
        return self.masked_number

    @property
    def masked_number(self):
        return u'XXXX%s' % self.last4_number

    def set_last4_number(self):
        self.last4_number = self.number[-4:]
        return self.last4_number


@receiver(pre_save, sender=Card)
def set_last4_number(instance, **kwargs):
    instance.set_last4_number()

ppars/apps/accounts/views.py
import logging
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, View, DeleteView
from ppars.apps.accounts.forms import PparsStrengthUserCreationForm, \
    UserEditForm
from ppars.apps.core.models import UserProfile

logger = logging.getLogger('ppars')


def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                if UserProfile.objects.get(user=user).is_license_expiries():
                    login(request, user)
                    if 'next' in request.GET:
                        return HttpResponseRedirect(request.GET['next'])
                    return HttpResponseRedirect('/')
                else:
                    return render(request, 'registration/login.html', {'license_limit': True})
        else:
            return render(request, 'registration/login.html', {'error': True})
    if request.GET:
        return render(request, 'registration/login.html')
    return HttpResponseRedirect('/')


class UserList(ListView):
    model = User
    template_name = 'accounts/user_list.html'
    context_object_name = 'user_list'

    def get_queryset(self):
        return self.request.user.profile.get_company_users()


class UserCreate(View):
    form_class = PparsStrengthUserCreationForm
    model = User
    template_name = 'accounts/user_form.html'

    def get(self, request, *args, **kwargs):
        form = PparsStrengthUserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = PparsStrengthUserCreationForm(request.POST)
        if form.is_valid():
            self.object = added_user = form.save(commit=True)
            p = added_user.profile
            p.company = self.request.user.profile.company
            p.save()
            messages.add_message(self.request, messages.SUCCESS, 'User "%s" created successfully.'% added_user)
            return render(request, 'accounts/user_list.html',
                          {
                           'user_list': request.user.profile.get_company_users(),
                          })
        else:
            logger.debug(form.errors)
            return render(request, self.template_name, {'form': form})


class UserUpdate(View):
    form_class = UserEditForm
    model = User
    template_name = 'accounts/user_form_edit.html'

    def get(self, request, pk, *args, **kwargs):
        user = get_object_or_404(User, pk=pk)
        form = UserEditForm(initial={
            'login':  user.username,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            })
        return render(request, self.template_name, {'form': form, 'object': user})

    def post(self, request, pk, *args, **kwargs):
        user = get_object_or_404(User, pk=pk)
        form = UserEditForm(request.POST)
        if form.is_valid():
            self.object = user = form.save()
            messages.add_message(self.request, messages.SUCCESS, 'User "%s" updated successfully.' % user)
            return render(request, 'accounts/user_list.html',
                          {
                           'user_list': request.user.profile.get_company_users(),
                          })
        else:
            logger.debug(form.errors)
            return render(request, self.template_name, {'form': form, 'object': user})


class UserDelete(DeleteView):
    model = User
    template_name = 'accounts/user_confirm_delete.html'

    def get_success_url(self):
        return reverse('user_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        # rel = UserProfile.objects.get(user=self.object)
        # rel.company = None
        # rel.save()
        self.object.delete()
        messages.add_message(self.request, messages.ERROR, 'User "%s" deleted successfully.' % self.object)
        return HttpResponseRedirect(self.get_success_url())

ppars/apps/api/views.py
from decorators import json_response
from ppars.apps.core.models import News
from pytz import timezone


@json_response
def ajax_ez_news(request):
    ajax_response = [{'title': news.title, 'message': news.message,
                      'created': news.created.astimezone(timezone('US/Eastern')).strftime("%m/%d/%y %I:%M:%S%p")}
                     for news in News.objects.filter(category='EZ').order_by('-created')]
    return ajax_response

ppars/apps/card/views.py
from django.shortcuts import render

# Create your views here.

ppars/templates/accounts/user_confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}
    <section class="content-header">
        <h1>
            Delete User
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'user_list' %}">Users</a></li>
			<li><a href="{% url 'user_update' user.id%}">{{ object }}</a></li>
			<li class='active'>Delete</li>       
        </ol>
    </section>
    <section class="content">
	    	<div class="box box-danger">
				<div class="box-header">
					<h3 class="box-title">Delete User: {{ object }}</h3>
				</div>
				<form class="form-horizontal" role="form" method="post" action=".">
      				{% csrf_token %}
      			<div class="form-group">
					<div class="col-sm-offset-1">
          				<label class="control-label" for="submit">
          				Are you sure you want to delete User "{{ object }}"?</label><br/>
					</div>
      			</div>
				<div class="box-footer">
					<div class="col-sm-offset-1">
      	  				<button type="submit" class="btn btn-danger">Delete</button>
      	  				<a href="{% url 'user_list' %}" class="btn btn-default">Cancel</a>
    				</div>
				</div>
                </form>
      		</div>
   </section>
{% endblock %}
{% block body_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__settings ul').css('display', 'block');
            $('#__settings').addClass( "active" );
            $('#__user').addClass( "active" );
        });
    </script>
{% endblock %}

ppars/templates/accounts/user_form.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="content-header">
        <h1>
            Manage Users
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
	        <li class='active'>My Settings</li>
        </ol>
    </section>
    	<section class="content">
        <div id="create-user-form" class="col-sm-8">
        {% crispy form %}
        </div>
      </section>
{% endblock %}
{% block body_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__settings ul').css('display', 'block');
            $('#__settings').addClass( "active" );
            $('#__user').addClass( "active" );
        });
    </script>
{% endblock %}

ppars/templates/accounts/user_form_edit.html
{% extends 'core/base.html' %}

{% block content %}
<section class="content-header" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
        <h1>
            Manage Users
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
	        <li class='active'>My Settings</li>
        </ol>
    </section>
    {% if form.errors %}
      {% for key, value in form.errors.items %}
	 <div class="alert alert-danger alert-dismissable">
           <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
           {{key}}{{value}}
         </div>
      {% endfor %}
    {% endif %}
    	<section class="content">
    <form class="form-horizontal user-form" role="form" method="post" action="." id="main">
      {% csrf_token %}
                <div class="form-group" id="div_login">
					<label for="id_login" class="col-sm-2 control-label">Login</label>
					<div class="col-sm-4">
                        <div>{{ object.username }}</div>
                        <input id="id_login"  type="hidden" name="login" class="form-control" value="{{ object.username }}"/>
						<span class="help-block" id="help_login"></span>
					</div>
      			</div>
                <div class="form-group" id="div_first_name">
					<label for="id_first_name" class="col-sm-2 control-label">First Name</label>
					<div class="col-sm-4">
						<input id="id_first_name" name="first_name" type="text" class="form-control" value="{{form.first_name.value|default_if_none:"" }}"/>
						<span class="help-block" id="help_first_name"></span>
					</div>
      			</div>
                <div class="form-group" id="div_last_name">
					<label for="id_last_name" class="col-sm-2 control-label">Last Name</label>
					<div class="col-sm-4">
						<input id="id_last_name" name="last_name" type="text" class="form-control" value="{{form.last_name.value|default_if_none:"" }}"/>
						<span class="help-block" id="help_last_name"></span>
					</div>
      			</div>
                <div class="form-group" id="div_email">
					<label for="id_email" class="col-sm-2 control-label">E-Mail</label>
					<div class="col-sm-4">
						<input id="id_email" name="email" type="email" class="form-control" value="{{form.email.value|default_if_none:"" }}"/>
						<span class="help-block" id="help_email"></span>
					</div>
      			</div>
                <div class="form-group" id="div_update_email">
					<label for="id_update_email" class="col-sm-2 control-label">News emails</label>
					<div class="col-sm-4">
						<input id="id_update_email" name="update_email" type="email" class="form-control" value="{{object.profile.updates_email|default_if_none:"" }}"/>
						<span class="help-block" id="help_update_email">Enter here comma separated list of emails. We will send all news about updates of the system on this emails. Leave it blank if you don't want to receive an emails. </span>
					</div>
      			</div>
        <div class="box-footer">
					<div class="col-sm-offset-2">
					  <button type="button" onclick="news_email_change()" class="btn btn-primary">Save</button>
                     {% if object and object.id != user.id %}<a href="{% url 'user_delete' object.id %}" class="btn btn-danger">Delete</a>{% endif %}
					  <a href="{% url 'user_list' %}" class="btn btn-default">Cancel</a>
					</div>
				  </div>
    </form>

      </section>
{% endblock %}
{% block body_js %}
    <script type="text/javascript">
        function news_email_change(){
            $.ajax({
                type : "GET",
                url : "/change_user",
                data: { news_email: $('#id_update_email').val() },
                dataType: "json",
                success: function(result) {
                    if(result['valid']){
                        $('.user-form').submit();
                        $('#div_update_email').removeClass('has-error');
                    }
                    else{
                        $('#div_update_email').addClass('has-error');
                    }
                }
            });
        }
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__settings ul').css('display', 'block');
            $('#__settings').addClass( "active" );
            $('#__user').addClass( "active" );
        });
    </script>
{% endblock %}

ppars/templates/accounts/user_list.html
{% extends 'core/base.html' %}

{% block add_css %}
    <link href="{{ STATIC_URL }}css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block content %}
    <section class="content-header">
        <h1>
            Manage Users
            <a class="btn btn-primary" href="{% url 'user_create' %}"><i class="fa fa-plus"></i> Add User</a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Users</li>
        </ol>
    </section>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'INFO' %}
                <div class="alert alert-info alert-dismissable">
            {% elif message.tags == 'success' %}
                <div class="alert alert-success alert-dismissable">
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissable">
            {% else %}
                <div class="alert alert-warning alert-dismissable">
            {% endif %}
                    <button type="button" class="close" data-dismiss="alert"
                            aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
        {% endfor %}
    {% endif %}
    <section class="content">
		<div class="box">
			<div class="box-body table-responsive">
				<table class="table table-condensed" id="datatable">
	                <thead>
	                    <tr>
	                        <th>#</th>
	                        <th>User</th>
	                        <th>First Name</th>
	                        <th>Last Name</th>
	                        <th>Email</th>
	                    </tr>
	                </thead>
	                <tbody>
	                {% for user in user_list %}
	                    <tr>
                            <td>{{ forloop.counter }}</td>
	                        <td><a href="{% url 'user_update' user.id%}">{{ user }}</a></td>
	                        <td>{{ user.first_name }}</td>
	                        <td>{{ user.last_name }}</td>
	                        <td>{{ user.email }}</td>
	                    </tr>
	                {% endfor %}
	                </tbody>
	            </table>
            </div>
        </div>
	</section>
{% endblock %}
{% block body_js %}
	<script src="{{ STATIC_URL }}js/datatables/jquery.dataTables.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__settings ul').css('display', 'block');
            $('#__settings').addClass( "active" );
            $('#__user').addClass( "active" );
        });
    </script>
{% endblock %}