ppars/apps/notification/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from views import SpamMessageCreate, CustomPreChargeMessageDetail, WelcomeEmailList, WelcomeEmailCreate,\
    WelcomeEmailEdit, welcome_message_delete


urlpatterns = patterns('',
    url(r'^create/$', login_required(SpamMessageCreate.as_view()), name='sms_create'),
    url(r'^precharge/$', login_required(CustomPreChargeMessageDetail.as_view()), name='custom_message'),
    url(r'^welcome_email/$', login_required(WelcomeEmailList.as_view()), name='welcome_email'),
    url(r'^welcome_email_create/$', login_required(WelcomeEmailCreate.as_view()), name='welcome_email_create'),
    url(r'^welcome_email_edit/(?P<pk>\d+)/$', login_required(WelcomeEmailEdit.as_view()), name='welcome_email_edit'),
    url(r'^welcome_message_delete/(?P<pk>\d+)/$', login_required(welcome_message_delete),
        name='welcome_message_delete'),
)

ppars/apps/price/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from ppars.apps.price.views import PlanSellingPriceList, PlanSellingPriceUpdate


urlpatterns = patterns('',
    url(r'^/$', login_required(PlanSellingPriceList.as_view()), name="plan_selling_price_list"),
    url(r'^/(?P<pk>\d+)/$', login_required(PlanSellingPriceUpdate.as_view()), name='plan_selling_price_update'),
)

ppars/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.conf.urls.static import static
from ppars.apps.accounts.views import UserList, UserCreate, UserUpdate, \
    UserDelete
from ppars.apps.charge.views import ChargeList, ChargeDetail, ajax_charge_steps, \
    ajax_mark_charge, ajax_cc_retry, ajax_cc_refund, ajax_cc_void, \
    ajax_charge_create, ajax_charges_list, ajax_change_charge_note, ajax_cc_retry_and_trans_restart
from ppars.apps.core import views
from ppars.apps.notification.views import ez_cloud_news_emails, change_ez_email_list
from ppars.apps.api import views as api


from ppars.apps.search.views import ajax_search, search, ajax_search_dropdown
# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    #url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^login/$', 'ppars.apps.accounts.views.login_user'),
    url(r'^logout.*', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    url(r'^user/password-change/$', 'django.contrib.auth.views.password_change', name="password_change"),
    url(r'^user/password-change-done/$', 'django.contrib.auth.views.password_change_done', name="password_change_done"),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'password_reset_done'}, name='password_reset'),
    #TODO normalize tokens
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
       'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done',
        name='password_reset_done'),

    url(r'^user/profile/$', login_required(views.CompanyProfileUpdate.as_view()), name="profile"),
    url(r'^change_user/$', login_required(views.change_user), name="change_user"),

    #API
    url(r'^ajax_ez_news/$', api.ajax_ez_news, name="ajax_ez_news"),

    # Ez Cloud News
    url(r'^ez_cloud_news_emails/$', login_required(ez_cloud_news_emails), name="ez_cloud_news_emails"),
    url(r'^change_ez_email_list/$', login_required(change_ez_email_list), name="change_ez_email_list"),

    url(r'^home/$', login_required(views.Home.as_view()), name="home"),
    url(r'^search/$', login_required(search), name="search"),
    url(r'^ajax_search/$', login_required(ajax_search), name="ajax_search"),
    url(r'^ajax_search_dropdown/$', login_required(ajax_search_dropdown), name="ajax_search_dropdown"),
    url(r'^ajax_refill_as_walk_in/$', login_required(views.ajax_refill_as_walk_in), name="ajax_refill_as_walk_in"),
    
    

    url(r'^customer$', login_required(views.CustomerList.as_view()), name="customer_list"),
    url(r'^customer/create/$', login_required(views.CustomerCreate.as_view()), name='customer_create'),
    url(r'^customer/(?P<pk>\d+)/$', login_required(views.CustomerUpdate.as_view()), name='customer_update'),
    url(r'^customer/(?P<pk>\d+)/delete/$', login_required(views.CustomerDelete.as_view()), name='customer_delete'),
    url(r'^customer/export/$', login_required(views.CustomerExport.as_view()), name='customer_export'),
    url(r'^customer/import/$', login_required(views.CustomerImport.as_view()), name='customer_import'),
    url(r'^customer/transactions/(?P<pk>\d+)/$', login_required(views.customer_transactions), name='customer_transactions'),
    url(r'^ajax_customer_transactions/$', login_required(views.ajax_customer_transactions), name='ajax_customer_transactions'),
    url(r'^customer/autorefills/(?P<pk>\d+)/$', login_required(views.customer_autorefills), name='customer_autorefills'),
    url(r'^ajax_customer_autorefills/$', login_required(views.ajax_customer_autorefills), name='ajax_customer_autorefills'),
    url(r'^customer/cc_charges/(?P<pk>\d+)/$', login_required(views.customer_cc_charges), name='customer_cc_charges'),
    url(r'^ajax_customer_cc_charges/$', login_required(views.ajax_customer_cc_charges), name='ajax_customer_cc_charges'),
    url(r'swipe_and_refill', login_required(views.SwipeAndRefill.as_view()), name="swipe_and_refill"),
    url(r'^ajax_check_duplicate_number/$', login_required(views.ajax_check_duplicate_number), name='ajax_check_duplicate_number'),

    url(r'^news$', login_required(views.news), name="news"),
    url(r'^news/(?P<pk>\d+)/$', login_required(views.NewsDetail.as_view()), name='news_detail'),
    url(r'^ajax_news/$', login_required(views.ajax_news), name='ajax_news'),
    url(r'^close_updates$', login_required(views.close_updates), name='close_updates'),

    url(r'^plan$', login_required(views.PlanList.as_view()), name="plan_list"),
    url(r'^plan/create/$', login_required(views.PlanCreate.as_view()), name='plan_create'),
    url(r'^plan/(?P<pk>\d+)/$', login_required(views.PlanUpdate.as_view()), name='plan_update'),
    url(r'^plan/(?P<pk>\d+)/delete/$', login_required(views.PlanDelete.as_view()), name='plan_delete'),
    url(r'^plan/export/$', login_required(views.PlanExport.as_view()), name='plan_export'),
    url(r'^plan/import/$', login_required(views.PlanImport.as_view()), name='plan_import'),

    url(r'^plan-discount$', login_required(views.PlanDiscountList.as_view()), name="plan_discount_list"),
    url(r'^plan-discount/create/$', login_required(views.PlanDiscountCreate.as_view()), name='plan_discount_create'),
    url(r'^plan-discount/(?P<pk>\d+)/$', login_required(views.PlanDiscountUpdate.as_view()), name='plan_discount_update'),

    url(r'^carrier$', login_required(views.CarrierList.as_view()), name="carrier_list"),
    url(r'^carrier/create/$', login_required(views.CarrierCreate.as_view()), name='carrier_create'),
    url(r'^carrier/(?P<pk>\d+)/$', login_required(views.CarrierUpdate.as_view()), name='carrier_update'),
    url(r'^carrier/(?P<pk>\d+)/delete/$', login_required(views.CarrierDelete.as_view()), name='carrier_delete'),
    url(r'^carrier/export/$', login_required(views.CarrierExport.as_view()), name='carrier_export'),
    url(r'^carrier/import/$', login_required(views.CarrierImport.as_view()), name='carrier_import'),

    url(r'^carrier-admin$', login_required(views.CarrierAdminList.as_view()), name="carrier_admin_list"),
    url(r'^carrier-admin/create/$', login_required(views.CarrierAdminCreate.as_view()), name='carrier_admin_create'),
    url(r'^carrier-admin/(?P<pk>\d+)/$', login_required(views.CarrierAdminUpdate.as_view()), name='carrier_admin_update'),

    url(r'^manualrefill$', login_required(views.ManualRefill.as_view()), name="manualrefill"),

    url(r'^autorefill$', login_required(views.AutoRefillList.as_view()), name="autorefill_list"),
    url(r'^autorefill/create/$', login_required(views.AutoRefillCreate.as_view()), name='autorefill_create'),
    url(r'^autorefill/(?P<pk>\d+)/$', login_required(views.AutoRefillUpdate.as_view()), name='autorefill_update'),
    url(r'^autorefill/(?P<pk>\d+)/delete/$', login_required(views.AutoRefillDelete.as_view()), name='autorefill_delete'),
    url(r'^autorefill/export/$', login_required(views.AutoRefillExport.as_view()), name='autorefill_export'),
    url(r'^autorefill/import/$', login_required(views.AutoRefillImport.as_view()), name='autorefill_import'),
    url(r'^ajax_check_for_similar_scheduled_refill/$', login_required(views.ajax_check_for_similar_scheduled_refill), name='ajax_check_for_similar_scheduled_refill'),

    url(r'^ajax_unused_pins$', login_required(views.ajax_unused_pins), name="ajax_unused_pins"),
    url(r'^unused-pin$', login_required(views.UnusedPinList.as_view()), name="unusedpin_list"),
    url(r'^unused-pin/create/$', login_required(views.UnusedPinCreate.as_view()), name='unusedpin_create'),
    url(r'^unused-pin/import/$', login_required(views.UnusedPinImport.as_view()), name='unusedpin_import'),
    url(r'^unused-pin/(?P<pk>\d+)/$', login_required(views.UnusedPinUpdate.as_view()), name='unusedpin_update'),
    url(r'^unused-pin/(?P<pk>\d+)/delete/$', login_required(views.UnusedPinDelete.as_view()), name='unusedpin_delete'),
    url(r'^ajax/ajax_mark_unusedpin/$', login_required(views.ajax_mark_unusedpin), name='ajax_mark_unusedpin'),

    url(r'^transaction$', login_required(views.TransactionList.as_view()), name="transaction_list"),
    url(r'^transaction/(?P<pk>\d+)/$', login_required(views.TransactionDetail.as_view()), name='transaction_detail'),
    url(r'^transaction/(?P<pk>\d+).json$', login_required(views.ajax_transaction), name='ajax_transaction'),

    url(r'^pin-report$', login_required(views.PinReportList.as_view()), name="pinreport_list"),
    url(r'^pin-report/(?P<pk>\d+)/$', login_required(views.PinReportDetail.as_view()), name='pinreport_detail'),
    url(r'^pin-report/compare/$', login_required(views.compare_pins_with_dollarphone), name='compare_pins_with_dollarphone'),
    url(r'^pin-report/download/(?P<order_id>\d+)/$', login_required(views.pinreport_download), name='pinreport_download'),

    url(r'^twilio_request/$', views.twilio_request, name='twilio_request'),
    url(r'^twilio_response/$', views.twilio_response, name='twilio_response'),
    url(r'^pparsb-response/(?P<pk>\d+)/$', views.pparsb_response, name='pparsb_response'),

    url(r'^confirm-dp/$', login_required(views.ConfirmDPView.as_view()), name='confirm_dp'),
    url(r'^logs/$', login_required(views.LogList.as_view()), name="log_list"),

    url(r'^import/customers/from-usaepay/$', login_required(views.import_customers_from_usaepay), name='import_customers_from_usaepay'),
    url(r'^import/customers/from-redfin/$', login_required(views.import_customers_from_redfin), name='import_customers_from_redfin'),

ppars/apps/accounts/models.py
from django.db import models

# Create your models here.

ppars/apps/price/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save, post_save, pre_delete
from django.dispatch import receiver
from gadjo.requestprovider.signals import get_request
from ppars.apps.core import fields
from ppars.apps.core.models import Plan, Carrier, CompanyProfile, Log


class SellingPriceLevel(models.Model):
    level = models.CharField(max_length=1)
    created = models.DateTimeField('Created at', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Updated at', auto_now=True)

    def __unicode__(self):
        return u'%s level price' % self.level


class PlanSellingPrice(models.Model):
    carrier = fields.BigForeignKey(Carrier)
    plan = fields.BigForeignKey(Plan)
    company = fields.BigForeignKey(CompanyProfile)
    price_level = models.ForeignKey(SellingPriceLevel)
    selling_price = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    created = models.DateTimeField('Created at', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Updated at', auto_now=True)

    def __unicode__(self):
        return u'%s level price for %s' % (self.price_level.level, self.plan.plan_id)

    def get_absolute_url(self):
        return reverse('plan_selling_price_list')


def level_price_default():
    return SellingPriceLevel.objects.get(level='1')

list_of_models = ('SellingPriceLevel', 'PlanSellingPrice')

@receiver(pre_save)
def logging_update(sender, instance, **kwargs):
    if instance.pk and sender.__name__ in list_of_models:
        from django.forms.models import model_to_dict

        company = None
        user_str = "System"

        if 'company' in dir(instance) and instance.company:
            company = instance.company

        http_request = get_request()
        if http_request:
            request_user = get_request().user
            user_str = 'User %s' % request_user
            if not company:
                if not request_user.is_authenticated():
                    # if 'User AnonymousUser' == user_str:
                    user_str = 'Anonymous User'
                elif request_user.profile.company:
                    company = request_user.profile.company

        new_values = model_to_dict(instance)
        old_values = sender.objects.get(pk=instance.pk).__dict__
        for key in new_values.keys():
            if key not in old_values.keys():  # because there is a things in new_values that we don't need
                new_values.pop(key, None)
        changed = [key for key in new_values.keys() if ((old_values[key] != new_values[key]) and
                                                        not ((old_values[key] is None and new_values[key] == '')
                                                             or (old_values[key] == '' and new_values[key] is None)))]
        if len(changed) > 0:
            update = ''
            for key in changed:
                update += key.replace('_', ' ').upper() + ': from ' + str(old_values[key]) + ' to ' + str(new_values[key]) + '; '
            note = '%s updated %s: %s \n' % (user_str, sender.__name__, str(instance))
            note += update
            Log.objects.create(company=company, note=note)

ppars/apps/notification/forms.py
from django import forms
from models import SpamMessage, CustomPreChargeMessage, WelcomeEmail


class SpamMessageForm(forms.ModelForm):
    class Meta:
        model = SpamMessage
        fields = ['message', 'customer_type', 'send_with', 'schedule_type', 'charge_type', 'carrier']


class CustomPreChargeMessageForm(forms.ModelForm):
    class Meta:
        model = CustomPreChargeMessage


class WelcomeEmailForm(forms.ModelForm):
    class Meta:
        model = WelcomeEmail
        exclude = ['company']

ppars/apps/price/forms.py
from django import forms
from ppars.apps.price.models import PlanSellingPrice


class PlanSellingPriceForm(forms.ModelForm):

    # def clean(self):
    #     cleaned_data = super(PlanSellingPriceForm, self).clean()
    #     if self.instance.id:
    #         psp = PlanSellingPrice.objects.exclude(id=self.instance.id).filter(plan=cleaned_data['plan'],
    #                                                price_level=cleaned_data['price_level'],
    #                                                company_id=cleaned_data['company'])
    #     else:
    #         psp = PlanSellingPrice.objects.filter(plan=cleaned_data['plan'],
    #                                               price_level=cleaned_data['price_level'],
    #                                               company_id=cleaned_data['company'])
    #     if psp.exists():
    #         raise forms.ValidationError('Selling price level already exists for this plan.')
    #     return cleaned_data

    class Meta:
        model = PlanSellingPrice
        fields = ['carrier', 'plan', 'company', 'selling_price', 'price_level']

ppars/apps/api/views.py
from decorators import json_response
from ppars.apps.core.models import News
from pytz import timezone


@json_response
def ajax_ez_news(request):
    ajax_response = [{'title': news.title, 'message': news.message,
                      'created': news.created.astimezone(timezone('US/Eastern')).strftime("%m/%d/%y %I:%M:%S%p")}
                     for news in News.objects.filter(category='EZ').order_by('-created')]
    return ajax_response

ppars/apps/card/views.py
from django.shortcuts import render

# Create your views here.

ppars/apps/price/views.py
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from ppars.apps.price.models import PlanSellingPrice
from ppars.apps.price.forms import PlanSellingPriceForm


class PlanSellingPriceList(ListView):
    model = PlanSellingPrice

    def get_queryset(self):
        return PlanSellingPrice.objects.filter(company=self.request.user.profile.company)


class PlanSellingPriceUpdate(UpdateView):
    model = PlanSellingPrice
    form_class = PlanSellingPriceForm

ppars/templates/price/plansellingprice_confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}
    <section class="content-header">
        <h1>
            Manage Plans
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'plan_selling_price_list' %}">Plans</a></li>
            <li><a href="{% url 'plan_selling_price_update' plansellingprice.id %}">{{ plansellingprice }}</a></li>
            <li class='active'>Delete</li>
        </ol>
    </section>
    {% if form.errors %}
        {% for key, value in form.errors.items %}
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ key }}{{ value }}
            </div>
        {% endfor %}
    {% endif %}
    <section class="content">
        {% if plansellingprice and plansellingprice.company != user.profile.company %}
            <div class="error-page">
                <h2 class="headline text-info">403</h2>

                <div class="error-content">
                    <h3><i class="fa fa-warning text-yellow"></i> Forbidden Resource.</h3>
                    <p>
                        You are not authorized to access this resource.
                        Meanwhile, you may <a href="{% url 'home' %}">return to dashboard</a>.
                    </p>
                </div>
                <!-- /.error-content -->
            </div><!-- /.error-page -->
        {% else %}
            <div class="box box-danger">
                <div class="box-header">
                    <h3 class="box-title">Delete Plan Selling Price: {{ plansellingprice }}</h3>
                </div>
                <form class="form-horizontal" role="form" method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-offset-1">
                            <label class="control-label" for="submit">Are you sure you want to delete plan
                                "{{ plansellingprice }}" ?</label><br/>
                            Do Note that this will also delete all autorefills using this plan.
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-sm-offset-1">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a href="{% url 'plan_selling_price_list' %}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            </section>
        {% endif %}
{% endblock %}
{% block body_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__cnp').addClass("active");
            $('#__cnp ul').css('display', 'block');
            $('#__plansellingprice').addClass("active");
        });
    </script>
{% endblock %}

ppars/templates/price/plansellingprice_form.html
{% extends 'core/base.html' %}
{% block add_css %}
    <link href="{{ STATIC_URL }}css/selectize.bootstrap3.css" rel="stylesheet" type="text/css">
    <link href="{{ STATIC_URL }}css/selectize.css" rel="stylesheet" type="text/css">
    <link href="{{ STATIC_URL }}css/refill.css" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
    <section class="content-header">
        <h1>
            Manage Plan Selling Price
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'plan_selling_price_list' %}">Plans Selling Prices</a></li>
            <li class='active'>{% if plansellingprice %} {{ plansellingprice }} {% else %} New {% endif %}</li>
        </ol>
    </section>
    {% if form.errors %}
        {% for key, value in form.errors.items %}
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ key }}{{ value }}
            </div>
        {% endfor %}
    {% endif %}
    <section class="content">
        {% if plansellingprice and plansellingprice.company != user.profile.company %}
            <div class="error-page">
                <h2 class="headline text-info">403</h2>
                <div class="error-content">
                    <h3><i class="fa fa-warning text-yellow"></i> Forbidden Resource.</h3>
                    <p>
                        You are not authorized to access this resource.
                        Meanwhile, you may <a href="{% url 'home' %}">return to dashboard</a>.
                    </p>
                </div>
                <!-- /.error-content -->
            </div><!-- /.error-page -->
        {% else %}
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">{% if plansellingprice %} Edit Plan Selling Price:
                        {{ plansellingprice }} {% else %} Add New Plan Selling Price{% endif %}</h3>
                </div>
                <div class="box-body">
                    <form class="form-horizontal" role="form" method="post" action=".">
                        {% csrf_token %}
                        <div class="form-group {% if form.carrier.errors %}has-error{% endif %}">
                            <label class="col-sm-2 control-label">Carrier</label>
                            <div class="col-sm-2 control-label">
                                {{ plansellingprice.carrier }}
                            </div>
                        </div>
                        <div class="form-group {% if form.plan.errors %}has-error{% endif %}">
                            <label class="col-sm-2 control-label">Plan</label>
                            <div class="col-sm-2 control-label">
                                {{ plansellingprice.plan }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Price Level</label>
                            <div class="col-sm-2 control-label">
                                {{ plansellingprice.price_level  }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_selling_price" class="col-sm-2 control-label">Selling Price</label>
                            <div class="col-sm-2">
                                <input id="id_selling_price" name="selling_price" type="text" class="form-control"
                                       required value="{{ form.selling_price.value|default_if_none:'' }}"
                                       placeholder="price for level sales"/>
                            </div>
                        </div>
                        <input type="hidden" value="{{ plansellingprice.carrier.id  }}" id="id_carrier" name="carrier"/>
                        <input type="hidden" value="{{ plansellingprice.plan.id }}" id="id_plan" name="plan"/>
                        <input type="hidden" value="{{ plansellingprice.price_level.id }}" id="id_price_level" name="price_level"/>
                        <input type="hidden" value="{{ user.profile.company.id }}" id="id_company" name="company"/>
                        <div class="box-footer">
                            <div class="col-sm-offset-2">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a href="{% url 'plan_selling_price_list' %}" class="btn btn-default">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </section>
        {% endif %}
{% endblock %}
{% block body_js %}
    <script src="{{ STATIC_URL }}js/selectize.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__cnp').addClass("active");
            $('#__cnp ul').css('display', 'block');
            $('#__plansellingprice').addClass("active");
        });
    </script>
{% endblock %}

ppars/templates/price/plansellingprice_list.html
{% extends 'core/base.html' %}
{% load tz %}
{% block add_css %}
    <link href="{{ STATIC_URL }}css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block content %}
    <section class="content-header">
        <h1>
            Plans Selling Prices
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li class="active">Plans Selling Prices</li>
        </ol>
    </section>
    {% if messages %}
        {% for message in messages %}
            <div class="alert
	            {% if message.tags == 'INFO' %}
	                alert-info
	            {% elif message.tags == 'success' %}
	                alert-success
                {% elif message.tags == 'error' %}
                    alert-danger
                {% else %}
                    alert-warning
                {% endif %}
            alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <section class="content">
        <div class="box">
            <div class="box-body table-responsive">
                <table class="table table-condensed" id="datatable">
                    <thead>
                    <tr>
                        <th data-sort-initial="true">Selling Price</th>
                        <th>Carrier</th>
                        <th>Plan</th>
                        <th>Selling Price</th>
                        <th>Price Level</th>
                        <th>Created</th>
                        <th>Updated</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for plan_selling_price in object_list %}
                        <tr>
                            <td><a href="{% url 'plan_selling_price_update' plan_selling_price.id %}">{{ plan_selling_price }}</a></td>
                            <td>{{ plan_selling_price.carrier }}</td>
                            <td>{{ plan_selling_price.plan }}</td>
                            <td>{{ plan_selling_price.selling_price }}</td>
                            <td>{{ plan_selling_price.price_level }}</td>
                            <td nowrap>{{ plan_selling_price.created|timezone:"US/Eastern"|date:"m/d/y H:i" }}</td>
                            <td nowrap>{{ plan_selling_price.updated|timezone:"US/Eastern"|date:"m/d/y H:i" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
{#                    <tfoot>#}
{#                        <tr>#}
{#                            <th></th>#}
{#                            <th></th>#}
{#                            <th></th>#}
{#                            <th></th>#}
{#                            <th>#}
{#                                <select class="form-control" id="type-filter">#}
{#                                    <option value=''>All</option>#}
{#                                    <option>Domestic Pin</option>#}
{#                                    <option>Domestic Top-Up</option>#}
{#                                </select>#}
{#                            </th>#}
{#                            <th></th>#}
{#                            <th></th>#}
{#                        </tr>#}
{#                    </tfoot>#}
                </table>
            </div>
        </div>
    </section>
{% endblock %}
{% block body_js %}
    <script src="{{ STATIC_URL }}js/datatables/jquery.dataTables.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tooltip-activate').tooltip();
            $('#__cnp').addClass("active");
            $('#__cnp ul').css('display', 'block');
            $('#__plansellingprice').addClass("active");
            var table = $('#datatable').dataTable({
                "bPaginate": true,
                "bLengthChange": true,
                "bFilter": true,
                "bSort": true,
                "bInfo": true,
                "bAutoWidth": true,
                "aoColumnDefs": [
                    {
                        "aTargets": [1],
                        "bSortable": false
                    },
                    {
                        "aTargets": [1],
                        "bSearchable": false
                    }
                ]
            });
{#            $('#type-filter', this).change(function () {#}
{#                table.fnFilter($(this).val(), 7);#}
{#            });#}
        });
    </script>
{% endblock %}